import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "@/styles/tiptap.css";
import { ApolloProvider } from "@/components/atoms/common/ApolloProvider/ApolloProvider";
import { AppInitializer } from "@/components/atoms/common/AppInitializer/AppInitializer";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body className="font-sans antialiased  bg-gray-100">
        <ApolloProvider>
          <AppInitializer />
          {children}
        </ApolloProvider>
      </body>
    </html>
  );
}
